### PR TITLE
Test for browser process.version shim before evaluating semver

### LINKED ISSUE #48: Invalid Version
Example: http://requirebin.com/?gist=bc69275e7018060b69f2de0740c3eae6

Introduced when going from 0.4.2 to 0.5.2

`node_modules/semver/semver.js:284 Uncaught TypeError: Invalid Version: undefined`

### PR DESCRIPTION
**Pull request by drewbo**
Close #48 cc: @mapsam

### CODE REVIEW

**Comment by mapsam** [comment]
Good find @drewbo - thanks for the PR! Once this is 🍏 I can merge and deploy a patch fix.

cc @springmeyer - running into browserify incompatibility due to the usage of `process.version`.

**Comment by springmeyer** [comment]
One problem with this change is that browerify + node v6 will be broken. I would recommend changing the check to default to using the node v6 API for browserify. Also, this will be resolved when/if node v0.10.x support is dropped (#50), but I don't think we should do this now.

**Comment by springmeyer** [comment]
> One problem with this change is that browerify + node v6 will be broken.

Actually that would require browserify moving to modeling its zlib module on node v6 exactly. Because the `zlib` module in browerify has not been updated in 3 years I guess this is not a going to be problem in reality: https://github.com/substack/browserify-zlib. (current last commit as of now is https://github.com/substack/browserify-zlib/commit/1a408066d9ac707b8a8727346322160bf7c81edb. So, nevermind on my concern.

**Comment by drewbo** [comment]
Thanks for checking that out @springmeyer; if the `zlib` module in browserify gets updated would we need to make a change to this check?

**Pull request merged**
